import subprocess


def main():
    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """

    ############################################################################################
    # READ INPUT (READING FROM FILE)


    # READ INPUT (INTERACTIVELY FROM USER)


    # CREATING MF STRUCT


    # ANY UPKEEP STEPS REQUIRED


    ####### START OF QUERY PROCESSING #######
    # QUERY PROCESSING LOGIC (NEEDS TO BE INSERTED INTO body VARIABLE (SEE BELOW))
    ## SHOULD BE IN A BIG FOR-LOOP (JAKOB)

    ## MAX (FOR LOOP)


    ## MIN (FOR LOOP)


    ## COUNT (FOR LOOP)


    ## SUM (FOR LOOP)


    ## AVERAGE (FOR LOOP) (RELIES ON COUNT AND SUM)

    ####### END OF QUERY PROCESSING ####### 

    # INJECT FOR LOOPS INTO body VARIABLE


    ############################################################################################

    body = """
    for row in cur:
        if row['quant'] > 10:
            _global.append(row)
    """

    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    {body}
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code
    subprocess.run(["python", "_generated.py"])


if "__main__" == __name__:
    main()
